#!/system/bin/sh

SETGET=$1
CMD=$2
SETVAL=$3

KERNEL_PROP=/sdcard/.nAOSProm.prop
BUILD_PROP=/system/build.prop

help() {
    echo "
naospromctl usage:

naosprom <get|set> <prop> [<value to set>]

get:
  zram-size : display the zram disk size in octet (0 if disabled)
  lightbar-enable : is lightbar enable on boot ?
  kernel : kernel that will be flashed in the recovery
  hw-keys-layout : hw keys layout
  doze-brightness : brightness level for doze
  minfree : absolute min free for android low memory killer
  
set:
  zram-size <value in octet> : set the disk size (set 0 to disable zram)
  lightbar-enable <true|false> : enable or not lightbar below the screen
  kernel <standard|oc|oc_ultra> : kernel to use for the next flash of the rom
  hw-keys-layout : layout to use (0 for 2.3, 1 for 4.4+)
  doze-brightness <brightness> : set the brightness for doze (-1 to use the default configuration)
  minfree <value in KiB> : absolute min free for android low memory killer
"

    exit 1
}

[ $# -lt 2 ] && help
[ "$SETGET" == "set" ] && [ $# -ne 3 ] && help

case "$SETGET" in
    "get")

        case "$CMD" in
            "zram-size")
                /system/xbin/egrep '^sys.zram.size=' $BUILD_PROP 2>/dev/null | /system/xbin/cut -d= -f2
                ;;
            "kernel")
                echo "
                    (/system/xbin/egrep '^kernel=' $KERNEL_PROP 2>/dev/null || echo \"kernel=standard\") | /system/xbin/cut -d= -f2
                    " | su
                ;;
            "lightbar-enable")
                /system/xbin/egrep '^sys.lightbar.enable=' $BUILD_PROP 2>/dev/null | /system/xbin/cut -d= -f2
                ;;
            "hw-keys-layout")
                /system/xbin/egrep '^qemu.hw.mainkeys.layout=' $BUILD_PROP 2>/dev/null | /system/xbin/cut -d= -f2
                ;;
            "doze-brightness")
                /system/xbin/egrep '^sys.screen.doze.brightness=' $BUILD_PROP 2>/dev/null | /system/xbin/cut -d= -f2
                ;;
            "minfree")
                /system/xbin/egrep '^sys.ram.minfree=' $BUILD_PROP 2>/dev/null | /system/xbin/cut -d= -f2
                ;;
            *)
                help
                ;;
        esac
        
        #end get
        ;;
    
    "set")
    
        REMOUNT=0
        if (grep '/system' /proc/mounts | cut -d' ' -f4 | grep -q 'ro'); then
            REMOUNT=1
        fi
        
        case "$CMD" in
            "kernel")
                [ "$SETVAL" == "-1" ] && exit 0
                echo "
                    if ( egrep -q '^kernel=' $KERNEL_PROP 2>/dev/null ); then
                        sed -i \"s/^kernel=.*/kernel=$SETVAL/\" $KERNEL_PROP
                    else
                        echo \"kernel=$SETVAL\" >> $KERNEL_PROP
                    fi
                    " | su
                ;;
            "zram-size")
                [ "$SETVAL" == "-1" ] && exit 0
                if [ "$SETVAL" == "0" ]; then
                    ZRAMSTATE=false
                else
                    ZRAMSTATE=true
                fi

                echo "
                    [ $REMOUNT -eq 1 ] && mount -o remount,rw /system ;
                    sed -i \"s/^sys.zram.enable=.*/sys.zram.enable=$ZRAMSTATE/\" $BUILD_PROP ;
                    sed -i \"s/^sys.zram.size=.*/sys.zram.size=$SETVAL/\" $BUILD_PROP ;
                    [ $REMOUNT -eq 1 ] && mount -o remount,ro /system ;
                    " | su
                ;;
            "lightbar-enable")
                echo "
                    [ $REMOUNT -eq 1 ] && mount -o remount,rw /system ;
                    sed -i \"s/^sys.lightbar.enable=.*/sys.lightbar.enable=$SETVAL/\" $BUILD_PROP ;
                    [ $REMOUNT -eq 1 ] && mount -o remount,ro /system ;
                    " | su
                ;;
            "hw-keys-layout")
                echo "
                    [ $REMOUNT -eq 1 ] && mount -o remount,rw /system ;
                    sed -i \"s/^qemu.hw.mainkeys.layout=.*/qemu.hw.mainkeys.layout=$SETVAL/\" $BUILD_PROP ;
                    [ $REMOUNT -eq 1 ] && mount -o remount,ro /system ;
                    " | su
                ;;
            "doze-brightness")
                [ "$SETVAL" == "-2" ] && exit 0
                echo "
                    [ $REMOUNT -eq 1 ] && mount -o remount,rw /system ;
                    sed -i \"s/^sys.screen.doze.brightness=.*/sys.screen.doze.brightness=$SETVAL/\" $BUILD_PROP ;
                    [ $REMOUNT -eq 1 ] && mount -o remount,ro /system ;
                    " | su
                ;;
            "minfree")
                [ "$SETVAL" == "-2" ] && exit 0
                echo "
                    [ $REMOUNT -eq 1 ] && mount -o remount,rw /system ;
                    sed -i \"s/^sys.ram.minfree=.*/sys.ram.minfree=$SETVAL/\" $BUILD_PROP ;
                    [ $REMOUNT -eq 1 ] && mount -o remount,ro /system ;
                    " | su
                ;;
            *)                                                                                                               
                help                                                                                                         
                ;;
        esac
        
        #end set
        ;;

esac

exit 0

